channels:
- conda-forge
dependencies:
- python=3.8.8
- pip<=21.0.1
- pip:
  - mlflow==2.9.2
  - cloudpickle==1.6.0
  - numpy==1.20.1
  - packaging==20.9
  - psutil==5.9.7
  - pyyaml==5.4.1
  - scikit-learn==1.3.2
  - scipy==1.6.2
name: mlflow-env
